import type { TacoFood } from "./types";

// ─── TACO 4th Edition — Most common Brazilian foods ──────
// Source: NEPA/UNICAMP (Public Domain)
// Values per 100g
// Full table: https://www.cfn.org.br/wp-content/uploads/2017/03/taco_4_edicao_ampliada_e_revisada.pdf

export const TACO_FOODS: TacoFood[] = [
  // ═══ CEREAIS E DERIVADOS ═══
  {
    name: "Arroz, tipo 1, cozido",
    normalized: "arroz tipo 1 cozido",
    category: "cereais",
    kcal: 128,
    proteinG: 2.5,
    carbsG: 28.1,
    fatG: 0.2,
    fiberG: 1.6,
  },
  {
    name: "Arroz, integral, cozido",
    normalized: "arroz integral cozido",
    category: "cereais",
    kcal: 124,
    proteinG: 2.6,
    carbsG: 25.8,
    fatG: 1.0,
    fiberG: 2.7,
  },
  {
    name: "Macarrão, trigo, cozido",
    normalized: "macarrao trigo cozido",
    category: "cereais",
    kcal: 102,
    proteinG: 3.4,
    carbsG: 19.9,
    fatG: 0.5,
    fiberG: 1.5,
  },
  {
    name: "Pão, francês",
    normalized: "pao frances",
    category: "cereais",
    kcal: 300,
    proteinG: 8.0,
    carbsG: 58.6,
    fatG: 3.1,
    fiberG: 2.3,
  },
  {
    name: "Pão, forma, integral",
    normalized: "pao forma integral",
    category: "cereais",
    kcal: 253,
    proteinG: 7.9,
    carbsG: 49.9,
    fatG: 2.8,
    fiberG: 6.9,
  },
  {
    name: "Biscoito, cream cracker",
    normalized: "biscoito cream cracker",
    category: "cereais",
    kcal: 432,
    proteinG: 10.1,
    carbsG: 68.7,
    fatG: 14.4,
    fiberG: 3.0,
  },
  {
    name: "Farinha, mandioca, torrada",
    normalized: "farinha mandioca torrada",
    category: "cereais",
    kcal: 365,
    proteinG: 1.2,
    carbsG: 89.2,
    fatG: 0.3,
    fiberG: 6.4,
  },
  {
    name: "Aveia, flocos",
    normalized: "aveia flocos",
    category: "cereais",
    kcal: 394,
    proteinG: 13.9,
    carbsG: 66.6,
    fatG: 8.5,
    fiberG: 9.1,
  },
  {
    name: "Cuscuz, milho, cozido",
    normalized: "cuscuz milho cozido",
    category: "cereais",
    kcal: 113,
    proteinG: 2.6,
    carbsG: 22.5,
    fatG: 1.5,
    fiberG: 2.1,
  },
  {
    name: "Tapioca, goma",
    normalized: "tapioca goma",
    category: "cereais",
    kcal: 340,
    proteinG: 0.5,
    carbsG: 84.3,
    fatG: 0.1,
    fiberG: 0.5,
  },
  {
    name: "Pão de queijo, assado",
    normalized: "pao de queijo assado",
    category: "cereais",
    kcal: 363,
    proteinG: 5.4,
    carbsG: 34.2,
    fatG: 22.6,
    fiberG: 0.5,
  },
  {
    name: "Granola",
    normalized: "granola",
    category: "cereais",
    kcal: 421,
    proteinG: 10.0,
    carbsG: 71.4,
    fatG: 12.4,
    fiberG: 5.6,
  },

  // ═══ LEGUMINOSAS ═══
  {
    name: "Feijão, carioca, cozido",
    normalized: "feijao carioca cozido",
    category: "leguminosas",
    kcal: 76,
    proteinG: 4.8,
    carbsG: 13.6,
    fatG: 0.5,
    fiberG: 8.5,
  },
  {
    name: "Feijão, preto, cozido",
    normalized: "feijao preto cozido",
    category: "leguminosas",
    kcal: 77,
    proteinG: 4.5,
    carbsG: 14.0,
    fatG: 0.5,
    fiberG: 8.4,
  },
  {
    name: "Lentilha, cozida",
    normalized: "lentilha cozida",
    category: "leguminosas",
    kcal: 93,
    proteinG: 6.3,
    carbsG: 16.3,
    fatG: 0.5,
    fiberG: 7.9,
  },
  {
    name: "Grão de bico, cozido",
    normalized: "grao de bico cozido",
    category: "leguminosas",
    kcal: 130,
    proteinG: 6.7,
    carbsG: 19.4,
    fatG: 2.6,
    fiberG: 5.1,
  },

  // ═══ CARNES E OVOS ═══
  {
    name: "Frango, peito, sem pele, grelhado",
    normalized: "frango peito sem pele grelhado",
    category: "carnes",
    kcal: 159,
    proteinG: 32.0,
    carbsG: 0.0,
    fatG: 2.5,
    fiberG: 0.0,
  },
  {
    name: "Frango, coxa, sem pele, cozida",
    normalized: "frango coxa sem pele cozida",
    category: "carnes",
    kcal: 215,
    proteinG: 26.6,
    carbsG: 0.0,
    fatG: 11.8,
    fiberG: 0.0,
  },
  {
    name: "Frango, sobrecoxa, sem pele, cozida",
    normalized: "frango sobrecoxa sem pele cozida",
    category: "carnes",
    kcal: 233,
    proteinG: 24.8,
    carbsG: 0.0,
    fatG: 14.6,
    fiberG: 0.0,
  },
  {
    name: "Carne, bovina, bife, grelhado",
    normalized: "carne bovina bife grelhado",
    category: "carnes",
    kcal: 219,
    proteinG: 32.4,
    carbsG: 0.0,
    fatG: 9.3,
    fiberG: 0.0,
  },
  {
    name: "Carne, bovina, moída, refogada",
    normalized: "carne bovina moida refogada",
    category: "carnes",
    kcal: 212,
    proteinG: 26.7,
    carbsG: 0.0,
    fatG: 11.5,
    fiberG: 0.0,
  },
  {
    name: "Carne, bovina, acém, cozido",
    normalized: "carne bovina acem cozido",
    category: "carnes",
    kcal: 215,
    proteinG: 27.0,
    carbsG: 0.0,
    fatG: 11.2,
    fiberG: 0.0,
  },
  {
    name: "Carne, suína, lombo, assado",
    normalized: "carne suina lombo assado",
    category: "carnes",
    kcal: 210,
    proteinG: 29.3,
    carbsG: 0.0,
    fatG: 9.8,
    fiberG: 0.0,
  },
  {
    name: "Linguiça, suína, frita",
    normalized: "linguica suina frita",
    category: "carnes",
    kcal: 296,
    proteinG: 16.1,
    carbsG: 2.2,
    fatG: 25.0,
    fiberG: 0.0,
  },
  {
    name: "Salsicha, tipo hot dog",
    normalized: "salsicha tipo hot dog",
    category: "carnes",
    kcal: 253,
    proteinG: 12.0,
    carbsG: 4.4,
    fatG: 21.0,
    fiberG: 0.0,
  },
  {
    name: "Calabresa, cozida",
    normalized: "calabresa cozida",
    category: "carnes",
    kcal: 260,
    proteinG: 18.0,
    carbsG: 1.5,
    fatG: 20.5,
    fiberG: 0.0,
  },
  {
    name: "Presunto, porco",
    normalized: "presunto porco",
    category: "carnes",
    kcal: 128,
    proteinG: 18.0,
    carbsG: 1.8,
    fatG: 5.5,
    fiberG: 0.0,
  },
  {
    name: "Peixe, tilápia, filé, grelhado",
    normalized: "peixe tilapia file grelhado",
    category: "carnes",
    kcal: 128,
    proteinG: 26.2,
    carbsG: 0.0,
    fatG: 2.7,
    fiberG: 0.0,
  },
  {
    name: "Ovo, galinha, cozido",
    normalized: "ovo galinha cozido",
    category: "carnes",
    kcal: 146,
    proteinG: 13.3,
    carbsG: 0.6,
    fatG: 9.5,
    fiberG: 0.0,
  },
  {
    name: "Ovo, galinha, frito",
    normalized: "ovo galinha frito",
    category: "carnes",
    kcal: 240,
    proteinG: 15.6,
    carbsG: 0.6,
    fatG: 19.6,
    fiberG: 0.0,
  },

  // ═══ LATICÍNIOS ═══
  {
    name: "Leite, integral",
    normalized: "leite integral",
    category: "laticinios",
    kcal: 61,
    proteinG: 3.2,
    carbsG: 4.5,
    fatG: 3.2,
    fiberG: 0.0,
  },
  {
    name: "Leite, desnatado",
    normalized: "leite desnatado",
    category: "laticinios",
    kcal: 35,
    proteinG: 3.4,
    carbsG: 5.0,
    fatG: 0.2,
    fiberG: 0.0,
  },
  {
    name: "Queijo, minas, frescal",
    normalized: "queijo minas frescal",
    category: "laticinios",
    kcal: 264,
    proteinG: 17.4,
    carbsG: 3.2,
    fatG: 20.2,
    fiberG: 0.0,
  },
  {
    name: "Queijo, mussarela",
    normalized: "queijo mussarela",
    category: "laticinios",
    kcal: 330,
    proteinG: 22.6,
    carbsG: 3.0,
    fatG: 25.2,
    fiberG: 0.0,
  },
  {
    name: "Queijo, prato",
    normalized: "queijo prato",
    category: "laticinios",
    kcal: 360,
    proteinG: 22.7,
    carbsG: 1.9,
    fatG: 29.1,
    fiberG: 0.0,
  },
  {
    name: "Iogurte, natural",
    normalized: "iogurte natural",
    category: "laticinios",
    kcal: 51,
    proteinG: 4.1,
    carbsG: 5.5,
    fatG: 1.1,
    fiberG: 0.0,
  },
  {
    name: "Manteiga",
    normalized: "manteiga",
    category: "laticinios",
    kcal: 726,
    proteinG: 0.4,
    carbsG: 0.0,
    fatG: 82.4,
    fiberG: 0.0,
  },
  {
    name: "Requeijão, cremoso",
    normalized: "requeijao cremoso",
    category: "laticinios",
    kcal: 257,
    proteinG: 9.4,
    carbsG: 3.0,
    fatG: 23.5,
    fiberG: 0.0,
  },

  // ═══ FRUTAS ═══
  {
    name: "Banana, prata",
    normalized: "banana prata",
    category: "frutas",
    kcal: 98,
    proteinG: 1.3,
    carbsG: 26.0,
    fatG: 0.1,
    fiberG: 2.0,
  },
  {
    name: "Maçã, fuji",
    normalized: "maca fuji",
    category: "frutas",
    kcal: 56,
    proteinG: 0.3,
    carbsG: 15.2,
    fatG: 0.0,
    fiberG: 1.3,
  },
  {
    name: "Laranja, pêra",
    normalized: "laranja pera",
    category: "frutas",
    kcal: 37,
    proteinG: 1.0,
    carbsG: 8.9,
    fatG: 0.1,
    fiberG: 0.8,
  },
  {
    name: "Mamão, papaia",
    normalized: "mamao papaia",
    category: "frutas",
    kcal: 40,
    proteinG: 0.5,
    carbsG: 10.4,
    fatG: 0.1,
    fiberG: 1.0,
  },
  {
    name: "Manga, palmer",
    normalized: "manga palmer",
    category: "frutas",
    kcal: 72,
    proteinG: 0.4,
    carbsG: 19.4,
    fatG: 0.3,
    fiberG: 1.6,
  },
  {
    name: "Melancia",
    normalized: "melancia",
    category: "frutas",
    kcal: 33,
    proteinG: 0.9,
    carbsG: 8.1,
    fatG: 0.0,
    fiberG: 0.1,
  },
  {
    name: "Abacaxi",
    normalized: "abacaxi",
    category: "frutas",
    kcal: 48,
    proteinG: 0.9,
    carbsG: 12.3,
    fatG: 0.1,
    fiberG: 1.0,
  },
  {
    name: "Morango",
    normalized: "morango",
    category: "frutas",
    kcal: 30,
    proteinG: 0.9,
    carbsG: 6.8,
    fatG: 0.3,
    fiberG: 1.7,
  },
  {
    name: "Uva, itália",
    normalized: "uva italia",
    category: "frutas",
    kcal: 53,
    proteinG: 0.7,
    carbsG: 13.6,
    fatG: 0.2,
    fiberG: 0.9,
  },
  {
    name: "Abacate",
    normalized: "abacate",
    category: "frutas",
    kcal: 96,
    proteinG: 1.2,
    carbsG: 6.0,
    fatG: 8.4,
    fiberG: 6.3,
  },

  // ═══ VERDURAS E LEGUMES ═══
  {
    name: "Alface, crespa, crua",
    normalized: "alface crespa crua",
    category: "verduras",
    kcal: 11,
    proteinG: 1.3,
    carbsG: 1.7,
    fatG: 0.2,
    fiberG: 1.8,
  },
  {
    name: "Tomate, cru",
    normalized: "tomate cru",
    category: "verduras",
    kcal: 15,
    proteinG: 1.1,
    carbsG: 3.1,
    fatG: 0.1,
    fiberG: 1.2,
  },
  {
    name: "Cenoura, cozida",
    normalized: "cenoura cozida",
    category: "verduras",
    kcal: 30,
    proteinG: 0.8,
    carbsG: 6.7,
    fatG: 0.2,
    fiberG: 2.6,
  },
  {
    name: "Cebola, crua",
    normalized: "cebola crua",
    category: "verduras",
    kcal: 39,
    proteinG: 1.7,
    carbsG: 8.9,
    fatG: 0.1,
    fiberG: 2.2,
  },
  {
    name: "Batata, inglesa, cozida",
    normalized: "batata inglesa cozida",
    category: "verduras",
    kcal: 52,
    proteinG: 1.2,
    carbsG: 11.9,
    fatG: 0.0,
    fiberG: 1.3,
  },
  {
    name: "Batata doce, cozida",
    normalized: "batata doce cozida",
    category: "verduras",
    kcal: 77,
    proteinG: 0.6,
    carbsG: 18.4,
    fatG: 0.1,
    fiberG: 2.2,
  },
  {
    name: "Mandioca, cozida",
    normalized: "mandioca cozida",
    category: "verduras",
    kcal: 125,
    proteinG: 0.6,
    carbsG: 30.1,
    fatG: 0.3,
    fiberG: 1.6,
  },
  {
    name: "Abobrinha, cozida",
    normalized: "abobrinha cozida",
    category: "verduras",
    kcal: 15,
    proteinG: 0.8,
    carbsG: 3.1,
    fatG: 0.1,
    fiberG: 1.4,
  },
  {
    name: "Brócolis, cozido",
    normalized: "brocolis cozido",
    category: "verduras",
    kcal: 25,
    proteinG: 2.1,
    carbsG: 4.4,
    fatG: 0.3,
    fiberG: 3.4,
  },
  {
    name: "Couve, manteiga, refogada",
    normalized: "couve manteiga refogada",
    category: "verduras",
    kcal: 90,
    proteinG: 2.9,
    carbsG: 7.6,
    fatG: 5.5,
    fiberG: 4.3,
  },
  {
    name: "Pepino, cru",
    normalized: "pepino cru",
    category: "verduras",
    kcal: 10,
    proteinG: 0.7,
    carbsG: 2.0,
    fatG: 0.1,
    fiberG: 1.1,
  },
  {
    name: "Beterraba, cozida",
    normalized: "beterraba cozida",
    category: "verduras",
    kcal: 32,
    proteinG: 1.3,
    carbsG: 7.2,
    fatG: 0.0,
    fiberG: 1.9,
  },
  {
    name: "Milho verde, cozido",
    normalized: "milho verde cozido",
    category: "verduras",
    kcal: 96,
    proteinG: 3.2,
    carbsG: 18.7,
    fatG: 1.1,
    fiberG: 2.7,
  },

  // ═══ ÓLEOS E GORDURAS ═══
  {
    name: "Óleo, soja",
    normalized: "oleo soja",
    category: "oleos",
    kcal: 884,
    proteinG: 0.0,
    carbsG: 0.0,
    fatG: 100.0,
    fiberG: 0.0,
  },
  {
    name: "Azeite, oliva, extra virgem",
    normalized: "azeite oliva extra virgem",
    category: "oleos",
    kcal: 884,
    proteinG: 0.0,
    carbsG: 0.0,
    fatG: 100.0,
    fiberG: 0.0,
  },
  {
    name: "Margarina, vegetal",
    normalized: "margarina vegetal",
    category: "oleos",
    kcal: 596,
    proteinG: 0.0,
    carbsG: 0.4,
    fatG: 67.0,
    fiberG: 0.0,
  },

  // ═══ AÇÚCARES ═══
  {
    name: "Açúcar, refinado",
    normalized: "acucar refinado",
    category: "acucares",
    kcal: 387,
    proteinG: 0.0,
    carbsG: 99.5,
    fatG: 0.0,
    fiberG: 0.0,
  },
  {
    name: "Mel",
    normalized: "mel",
    category: "acucares",
    kcal: 309,
    proteinG: 0.3,
    carbsG: 84.0,
    fatG: 0.0,
    fiberG: 0.0,
  },

  // ═══ BEBIDAS ═══
  {
    name: "Café, infusão",
    normalized: "cafe infusao",
    category: "bebidas",
    kcal: 3,
    proteinG: 0.3,
    carbsG: 0.5,
    fatG: 0.0,
    fiberG: 0.0,
  },
  {
    name: "Suco, laranja, integral",
    normalized: "suco laranja integral",
    category: "bebidas",
    kcal: 45,
    proteinG: 0.6,
    carbsG: 10.4,
    fatG: 0.1,
    fiberG: 0.1,
  },

  // ═══ PREPARAÇÕES COMUNS ═══
  {
    name: "Farofa, mandioca",
    normalized: "farofa mandioca",
    category: "preparacoes",
    kcal: 436,
    proteinG: 1.5,
    carbsG: 67.2,
    fatG: 17.1,
    fiberG: 4.2,
  },
];
